--- #YAML:1.0
name:                Bundle-IO-Compress-Bzip2
version:             2.012
abstract:            Install IO::Compress::Bzip2 and dependencies
license:             perl
author:              
    - Paul Marquess <pmqs@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
